Add multiline strings
ClueLang/Clue pull request #34
Opened 2022-07-28 14:49 UTC by Markos-Th09

This PR adds multiline stings to clue. Although regular strings can span multiple lines any tab or newline characters are not preserved. This other type of multiline strings preserves those.

The ` symbol is used to denote multiline strings

```
print(`
hello
world
`)
```

When this program is run it should output

```
hello
world
```

2022-07-28 15:05 UTC, Maiori44 requested changes
Does it need to use its own ComplexToken?
Especially for 3.0 I would need it to use SYMBOL

2022-07-28 15:19 UTC, Markos-Th09 commented
> Does it need to use its own ComplexToken? Especially for 3.0 I would need it to use SYMBOL

The problem with SYMBOL is that it  is used in places where multiline string is invalid so I wasn't sure if it was a good idea to do that

2022-07-28 15:25 UTC, Maiori44 commented
SYMBOL can be compiled anywhere, you just have to parse multilined strings in the right place

2022-07-28 15:29 UTC, Markos-Th09 commented
> SYMBOL can be compiled anywhere, you just have to parse multilined strings in the right place

Hmm ok let me actually make a SYMBOL only implementation of this

2022-07-28 15:37 UTC, Markos-Th09 reviewed
Implemented it without a new ComplexToken

2022-07-29 10:13 UTC, Maiori44 reviewed
I can see a much simpler and faster way to implement this, can I merge this and then change it?

2022-07-29 11:53 UTC, Markos-Th09 commented
> I can see a much simpler and faster way to implement this, can I merge this and then change it?

Sure

2022-07-29 11:55 UTC, merged